from .src.model_src import Model
from .src.model_src.GeneralModel import GeneralModel
from .src.model_src.NbodyModel import NbodyModel
from .src.model_src.Plummer import Plummer
from .src.model_src.King import King
from .src.model_src.Sersic import Sersic
from .src.model_src.Plummer2D import Plummer2D
from .src.model_src.Tbetamodel import Tbetamodel
from .src.model_src.Model import Multimodel
from .src.model_src.Isothermal import Isothermal